<a href="https://colab.research.google.com/github/AshaArepalli7296/Sleep_Disorder/blob/main/Sleep_Disorder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as mtp

In [ ]:
data_set= pd.read_csv('expanded_sleep_health_dataset.csv')
print(data_set)

      Person ID  Gender  Age         Occupation  Sleep Duration  \
0             1    Male   41              Nurse             7.0   
1             2    Male   42  Software Engineer             6.7   
2             3  Female   45             Doctor             8.7   
3             4    Male   24             Writer             8.0   
4             5  Female   18        Salesperson             8.8   
...         ...     ...  ...                ...             ...   
1495       1496    Male   63           Engineer             9.1   
1496       1497    Male   70             Lawyer             8.6   
1497       1498    Male   23           Engineer             7.3   
1498       1499    Male   76           Engineer             8.1   
1499       1500  Female   22           Engineer             5.8   

      Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                    5                       91            10       Normal   
1                    7                 

In [ ]:
data_set = pd.read_csv('expanded_sleep_health_dataset.csv', keep_default_na=False)
print(data_set)


      Person ID  Gender  Age         Occupation  Sleep Duration  \
0             1    Male   41              Nurse             7.0   
1             2    Male   42  Software Engineer             6.7   
2             3  Female   45             Doctor             8.7   
3             4    Male   24             Writer             8.0   
4             5  Female   18        Salesperson             8.8   
...         ...     ...  ...                ...             ...   
1495       1496    Male   63           Engineer             9.1   
1496       1497    Male   70             Lawyer             8.6   
1497       1498    Male   23           Engineer             7.3   
1498       1499    Male   76           Engineer             8.1   
1499       1500  Female   22           Engineer             5.8   

      Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                    5                       91            10       Normal   
1                    7                 

In [ ]:
for col in data_set.columns:
    print(f"{col} → {data_set[col].unique()}")


Person ID → [   1    2    3 ... 1498 1499 1500]
Gender → ['Male' 'Female']
Age → [41 42 45 24 18 78 21 50 68 71 46 77 23 30 69 56 51 75 61 37 31 72 19 60
 20 39 35 64 58 33 73 79 36 67 43 49 38 40 65 44 57 63 53 54 26 29 62 66
 52 34 55 59 25 70 80 74 47 28 48 76 27 32 22]
Occupation → ['Nurse' 'Software Engineer' 'Doctor' 'Writer' 'Salesperson' 'Manager'
 'Lawyer' 'Artist' 'Accountant' 'Sales Representative' 'Engineer'
 'Scientist' 'Chef' 'Student' 'Teacher']
Sleep Duration → [ 7.   6.7  8.7  8.   8.8  7.7  6.8  7.2  7.5  8.5  7.3  8.2  7.8  7.4
  7.6  9.5  7.1  5.8  8.6 10.   6.4  8.3  9.   8.4  9.3  9.4  6.3  6.6
  6.5  9.1  8.1  6.9  5.5  7.9  9.2  5.7  9.9  6.   6.2  9.7  8.9  6.1
  5.6  9.6  5.2  5.4  5.3  9.8  5.9  5.1]
Quality of Sleep → [ 5  7  4  6  3  9  1  8  2 10]
Physical Activity Level → [ 91 123  49   4  66  34  35  30  37  26  23  93   7  59  65  68 142 127
  51 106  50  21  52  99   0 128  13  63 157  45  31  20  36  43 118  86
 100  22  16  14  79  53  58  42   2  67

In [ ]:
data_set.drop('Person ID', axis=1, inplace=True)


In [ ]:
data_set['Gender'] = data_set['Gender'].map({'Male': 0, 'Female': 1})


In [ ]:
data_set = pd.get_dummies(data_set, columns=['Occupation'], drop_first=True)


In [ ]:
bmi_order = {'Underweight': 0, 'Normal': 1, 'Overweight': 2, 'Obese': 3}
data_set['BMI Category'] = data_set['BMI Category'].map(bmi_order)


In [ ]:
data_set.drop('Blood Pressure', axis=1, inplace=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_features = ['Age', 'Sleep Duration', 'Quality of Sleep',
                      'Physical Activity Level', 'Stress Level']

data_set[numerical_features] = scaler.fit_transform(data_set[numerical_features])


In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data_set['Sleep Disorder'] = label_encoder.fit_transform(data_set['Sleep Disorder'])


In [ ]:
X = data_set.drop('Sleep Disorder', axis=1)
y = data_set['Sleep Disorder']


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Create and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Step 2: Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Step 3: Evaluate the model
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test,y_pred_rf))

Random Forest Accuracy: 0.6833333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.00      0.00      0.00        20
           2       0.69      1.00      0.82       202
           3       0.00      0.00      0.00        14
           4       0.44      0.12      0.20        32

    accuracy                           0.68       300
   macro avg       0.23      0.22      0.20       300
weighted avg       0.51      0.68      0.57       300


Confusion Matrix:
 [[  0   0  29   0   3]
 [  0   0  19   0   1]
 [  0   0 201   0   1]
 [  0   0  14   0   0]
 [  0   0  28   0   4]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
feature_columns = X_train.columns.tolist()

In [ ]:

def get_user_input():
    data = {
        'Gender': int(input("Enter Gender (0=Male, 1=Female): ")),
        'Age': float(input("Enter Age: ")),
        'Sleep Duration': float(input("Enter Sleep Duration (in hours): ")),
        'Quality of Sleep': float(input("Enter Quality of Sleep (1-10): ")),
        'Physical Activity Level': float(input("Enter Physical Activity Level (1-100): ")),
        'Stress Level': float(input("Enter Stress Level (1-10): ")),
        'BMI Category': int(input("Enter BMI Category (0=Underweight, 1=Normal, 2=Overweight, 3=Obese): ")),
        'Daily Steps': int(input("Enter Daily Steps: ")),
        # Adding missing feature and initializing it to 0
        'Heart Rate': 0  # Assuming resting heart rate or asking for it as input
    }

    # One-hot encoding for occupation
    occupation_list = ['Artist', 'Chef', 'Doctor', 'Engineer', 'Lawyer', 'Manager', 'Nurse',
                       'Sales Representative', 'Salesperson', 'Scientist',
                       'Software Engineer', 'Student', 'Teacher', 'Writer']

    occupation = input(f"Enter Occupation (choose from: {occupation_list}): ")

    # Initialize one-hot encoding for occupation
    for occ in occupation_list:
        data[f'Occupation_{occ}'] = 1 if occupation == occ else 0

    # Create DataFrame
    df_input = pd.DataFrame([data])

    # Ensure all columns from the trained model exist in input DataFrame
    for col in X_train.columns:  # Using X_train.columns for correct features
        if col not in df_input.columns:
            df_input[col] = 0  # Fill missing columns with 0

    # Scale numerical features
    numerical_features = ['Age', 'Sleep Duration', 'Quality of Sleep',
                          'Physical Activity Level', 'Stress Level']

    #Scaling the numerical features
    df_input[numerical_features] = scaler.transform(df_input[numerical_features])

    # Reorder to match the original feature order
    df_input = df_input[X_train.columns]  # Ensures correct order

    return df_input

# Get user input
user_input = get_user_input()

# Predict
prediction = rf_model.predict(user_input)

# Output result
classes = {0: 'Insomania', 1: 'Narcolepsy', 2: 'None', 3: 'Restless Leg Syndrome' , 4:'Sleep Apnea'}
print(f"\n🧾 Predicted Sleep Disorder Class: {classes[prediction[0]]}")

Enter Gender (0=Male, 1=Female): 1
Enter Age: 19
Enter Sleep Duration (in hours): 6
Enter Quality of Sleep (1-10): 5
Enter Physical Activity Level (1-100): 70
Enter Stress Level (1-10): 5
Enter BMI Category (0=Underweight, 1=Normal, 2=Overweight, 3=Obese): 1
Enter Daily Steps: 500
Enter Occupation (choose from: ['Artist', 'Chef', 'Doctor', 'Engineer', 'Lawyer', 'Manager', 'Nurse', 'Sales Representative', 'Salesperson', 'Scientist', 'Software Engineer', 'Student', 'Teacher', 'Writer']): Nurse

🧾 Predicted Sleep Disorder Class: None
